name: "New Release Tag"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    name: "Create Release From Tag"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: "Checkout release tag"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: "Install PHP 8.0"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          ini-values: phar.readonly=Off, error_reporting=-1, display_errors=On

      - name: "Install Composer dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: highest
          composer-options: --prefer-stable
          custom-cache-key: composer-${{ runner.os }}-php${{ matrix.php-versions }}-${{ hashFiles('**/composer.json') }}

      - name: "Create build directory"
        run: mkdir .build

      - name: "Capture tag message"
        run: git tag -l --format='%(contents)' | tail +3 > .build/tag_msg.txt

      - name: "Create PHAR archive"
        run: php .github/build-phar.php .build/example-skeleton.phar

      - name: "Create release Draft"
        uses: softprops/action-gh-release@v2
        with:
          name: 'Release version ${{ github.ref_name }}'
          body_path: .build/tag_msg.txt
          files: .build/example-skeleton.phar
          draft: true
          token: ${{ secrets.SHUDDER_ACTION_TOKEN }}
