name: "New Release Tag"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    name: "Create Release From Tag"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: "Checkout release tag"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: "Capture tag message"
        run: |
          mkdir .dev
          git tag -l --format='%(contents)' | tail +3 > .dev/tag_msg.txt

      - name: "Create release Draft"
        uses: softprops/action-gh-release@v2
        with:
          name: 'Release version ${{ github.ref_name }}'
          body_path: '.dev/tag_msg.txt'
          draft: true
          token: ${{ secrets.SHUDDER_ACTION_TOKEN }}
